name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Run dependency vulnerability scan
      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        continue-on-error: true   # ✅ Prevents job failure if issues found
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Code analysis (source code security)
      - name: Snyk Code Analysis
        run: snyk code test --sarif > snyk-code.sarif || true   # ✅ Avoid exit code 2 failure
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Upload results to GitHub Security tab
      - name: Upload results to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

